### ISSUE TITLE
Add saga example

### ISSUE THREAD

**Issue by tgrrr** [dai-shi/react-hooks-global-state#25]
Big fan.

Could we add an example of how to run with Sagas?

In particular, I'd just like to cover:
- side effects (eg. updating asyncronous data fetching), 
- ideally with middleware

**Comment by dai-shi** [comment]
Please give it a try.
Honestly, I'm not sure how it goes.
The way this library works is just **mimicking** Redux to some extent,
so there's no guarantee that all Redux libraries/tools work.

**Comment by serhii-holovko-ss** [comment]
hey @dai-shi . I see, since your previous comment version 1 has been released. Please let me know, if this can be used with redux-saga or other async handling middleware functions.
If so, I would be thankful for some example, how to set it up.

**Comment by dai-shi** [comment]
@serhii-holovko-ss Hi, v1 is stable in terms of documented API and its implementation, however, the support for redux middleware is not changed.

> The way this library works is just **mimicking** Redux to some extent,
> so there's no guarantee that all Redux libraries/tools work.

So, this still holds.

----

If you are interested in trying redux-saga, I can help. As a start, there's already an example with redux-thunk, so you want to check it to start with. https://github.com/dai-shi/react-hooks-global-state/tree/master/examples/08_thunk

**Comment by dai-shi** [comment]
v2 is released and closing this.
