### ISSUE TITLE
Error calling createStore (Typescript 3.6.4) 

### ISSUE THREAD

**Issue by pranav-xx** [dai-shi/react-hooks-global-state#29]
While calling createStore, getting following error

```
This expression is not callable
Each member of the union type 'CreateStore | CreateReduxLikeStore' has signatures, but none of these signatures are compatible with each other.
```
Note I am using Typescript version 3.6.4

I know this used to be an issue below Typescript 3.3. But it was fixed as stated in change logs. https://github.com/Microsoft/TypeScript/wiki/What's-new-in-TypeScript#typescript-33

**Comment by dai-shi** [comment]
Hm, that wouldn't be nice.
@pranav-xx Could you create a reproduction in codesandbox?

**Comment by dai-shi** [comment]
Closing this issue as stale.

Feel free to reopen this if the problem persists, hopefully with reproduction.

It's known that typing with createStore has some limitations. Contributions by TS experts would be appreciated.
