### ISSUE TITLE
How to use Redux Devtools Extension

### ISSUE THREAD

**Issue by hug0b** [dai-shi/react-hooks-global-state#37]
The README specifies

> Redux middleware support to some extent
> 
> Some of libraries in Redux ecosystem can be used.
> Redux DevTools Extension could be used in a simple scenario.

But I am not sure how to connect it to the store, could you provide an example ?

**Comment by dai-shi** [comment]
Currently, there's only one example. Please check out `examples/08_thunk`.

**Comment by rimsila** [comment]
@dai-shi  I can't use it in Next JS. It say windows of undefined.

**Comment by dai-shi** [comment]
@rimsila Thanks for reporting it. I would need someone to help with this.
Note: the devtools support is pretty hacky and limited. It might not work in some complex cases. But, the `undefined` error could be fixed.
