### ISSUE TITLE
Error: You cannot use <GlobalStateProvider> more than once.

### ISSUE THREAD

**Issue by Temirtator** [dai-shi/react-hooks-global-state#41]
![image](https://user-images.githubusercontent.com/10742084/79305672-a6efde00-7f15-11ea-9e4c-885f9485c98d.png)

1. This case happened, when user closing application but application living in back process
2. Open, for example: whatsapp or any other app
3. And then open my application again
But its not always... for some reason, i dont know
Thanks !!!

**Comment by dai-shi** [comment]
Thanks for reporting. I'm not sure why it happens either, but it means somehow GlobalStateProvider is used twice.
Please note that the latest version v1.0.0 (and the next version v2.0.0) doesn't have GlobalStateProvider anymore.

**Comment by Temirtator** [comment]
@dai-shi wow, thanks cool. when i can check next version?

**Comment by dai-shi** [comment]
Which version are you using now? I recommend upgrading to v1.0.0 at this point. API has breaking changes from v0.x, but it should be easy to migrate.

v2 is coming with newer React version and is not ready (and is not working fully yet, PR here #38)

**Comment by Temirtator** [comment]
I have version ^0.16.0.

Ok i'll check to 1.0.0

**Comment by Temirtator** [comment]
@dai-shi i updated the library, so after week, if there's no any errors, i will close issue
