### ISSUE TITLE
global state not preserved with Fast Refresh

### ISSUE THREAD

**Issue by miaowang** [dai-shi/react-hooks-global-state#50]
Hi, thanks for the repo. One thing that I noticed, is that the global state is not preserved with the Fast Refresh functionality. If code changes are done, then Fast Refresh kicks in to reload the UI, but in this case the global state is not preserved as I would have used useState normally. Is there a way to fix this?

**Comment by dai-shi** [comment]
Hi, I think I did best for fast refresh. The examples have fast refresh enabled. (Though, it's a bit old.)
You might want to separate a store file. It's not 100% same as useState anyway.
Can you create a codesandbox and explain the unexpected behavior? It can be a known limitation.

**Comment by dai-shi** [comment]
v2 is released and closing this.
