### ISSUE TITLE
Argument of type '"cart"' is not assignable to parameter of type 'never'

### ISSUE THREAD

**Issue by FutureKode** [dai-shi/react-hooks-global-state#51]
I have a NextJs project with typescript. I'm seeing the above error with useGlobalState and reducer style.

const [cart] = useGlobalState("cart") <-- Argument of type '"cart"' is not assignable to parameter of type 'never'

But I'm not sure what the problem is at it looks the same as the examples. Any ideas?

**Comment by dai-shi** [comment]
Hi, I need some more information.
1. how does `createGlobalState` look like? does it initialize `{ cart: ... }`?
2. can you repro the issue without nextjs? a codesandbox repro would be nice.

**Comment by FutureKode** [comment]
Hi @dai-shi 

This is the relative code:

```
import { createStore } from "react-hooks-global-state"

interface State {
  cart: Array<ICartItem>
  cookiesNoticeSeen: boolean
}

type Action =
  | { type: "rehydrate"; payload: any }
  | { type: "addItem"; item: ICartItem }
  | { type: "removeItem"; id: string }
  | { type: "setCookiesNoticeSeen" }

const defaultState: State = {
  cookiesNoticeSeen: false,
  cart: [],
}

const initialState: State = defaultState

const saveStateToStorage = ({ getState }: { getState: () => State }) => (
  next: Dispatch<Action>
) => (action: Action) => {
  const returnValue = next(action)
  if (isBrowser()) {
    localStorage.setItem(LOCAL_STORAGE_KEY, JSON.stringify(getState()))
  }
  return returnValue
}

export const { dispatch, useGlobalState } = createStore(
  reducer,
  initialState,
  applyMiddleware(saveStateToStorage)
)
```

**Comment by dai-shi** [comment]
It looks good...
Does removing middleware change things?
Can you repro with codesandbox?

**Comment by FutureKode** [comment]
I have found the lines in my code that are causing the issue.

```
case "rehydrate":   
      console.log('rehydrating', action)
      return action.payload
```

If I remove this code from my reducer then the errors go away

**Comment by FutureKode** [comment]
@dai-shi yep sorry about that, reworked my code and the error is gone 👻
