### ISSUE TITLE
Is it possible to change a value outside a component?

### ISSUE THREAD

**Issue by SrBrahma** [dai-shi/react-hooks-global-state#57]
In MobX, for example, I can change at any place a value that will cause the related components to re-render.

MobX would solve my issue, but, it's a bit of overkill, as your package is much lighter.

Is it possible to change a global state outside a component?

**Comment by dai-shi** [comment]
sure, that's the whole point of this library.

> setGlobalState: a function to set a global state by key outside React

```js
const { useGlobalState, setGlobalState } = createGlobalState({ count: 0 });

setGlobalState('count', 1);
```

**Comment by SrBrahma** [comment]
Damn, haha! I was hoping to get some workaround, not a built in way.

Thanks for the quick answer, and also, for the package!
