### ISSUE TITLE
Initialize with null

### ISSUE THREAD

**Issue by schneck** [dai-shi/react-hooks-global-state#6]
Hi,
a question: I would like to initialize a value with `null`, something like

```
const initialState = {
  user: null
};
```

```
const [_, setUser] = useGlobalState<IUser | null>("user");
```

I get an error:

```
Type error: Type 'IUser' does not satisfy the constraint '"user"'
```

Is there any workaround?

Thanks!

**Comment by dai-shi** [comment]
In this case, you probably need to add a type in createGlobalState. (as the useGlobalState type is inferred from it.)

```
type State = {
  user: IUser | null;
};

const { GlobalStateProvider, useGlobalState } = createGlobalState<State>(initialState);
```

**Comment by schneck** [comment]
Thanks, got it working that way.
