### ISSUE TITLE
How to update the state in Bulk ?

### ISSUE THREAD

**Issue by harishpydimarri29** [dai-shi/react-hooks-global-state#88]
We are using this library for maintaining authentication state.
As part of auth we are storing multiple user related values.
Is there a way to update all of them in oneshot like 
`setGlobalState(prvsState => ({...prvsState, ...updatedState}))`

**Comment by dai-shi** [comment]
No, but calling `setGlobalState()` multiple times in sync will be batched.

**Comment by harishpydimarri29** [comment]
Thanks for your quick reply
So its not possible in the createGlobalState
But in createStoreState we can update multiple values in the reducer right ? Or is it internally doing the state updates + renderings for each key update ?

**Comment by dai-shi** [comment]
Yes, the separation for each key is the design of this library. You won't lose any performance in terms of react rendering.

If you want more flexibility, consider using the underlying library, [zustand](https://github.com/pmndrs/zustand).
